#!/bin/bash

PLAYER=

if [ -x "`which aplay`" ]; then
	PLAYER=aplay
elif [ -x "`which afplay`" ]; then
	#afplay is shipped with OS X Leopard
	PLAYER=afplay
elif [ -x "`which play`" ]; then
	PLAYER=play
elif [ -x "`which mplayer`" ]; then
	PLAYER="mplayer -nogui -nocache"
fi

if [ "x${PLAYER}" = "x" ]; then
	echo "Can't find audio player!"
	echo "Please make sure you have aplay, play or mplayer in your path."
	if [ "`uname`" = "Darwin" ]; then
		echo "A working play for OS X is available from:"
		echo "http://www.hieper.nl/html/play.html"
	fi
else
	exec ${PLAYER} "$@" >/dev/null 2>&1
fi
